// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "#SOQOPOOOYOQO'#C_OOOO'#C^'#C^OOOO'#Cc'#CcQQOPOOOOOO'#Cd'#CdObOQO,58yOjOQO,58yOOOO-E6a-E6aOOOO-E6b-E6bOrOQO1G.eOrOQO1G.eOOOO1G.e1G.eOzOQO7+$POOOO7+$P7+$POOOO<<Gk<<Gk",
  stateData: "!S~OUQOYPO~OSTOTVO~OSTOTYO~OSTOZ[O~OSTOZ^O~OSTOZ_O~O",
  goto: "vXPPY^PPPbhTROSTQOSQSORWSQUPUXUZ]QZVR]Y",
  nodeNames: "⚠ TemplateString Expression VariableUse Space VariableName Text",
  maxTerm: 11,
  skippedNodes: [0],
  repeatNodeCount: 2,
  tokenData: "&[~RnOX#PX^#k^p#Ppq#kq!c#P!c!}%a!}#T#P#T#o%a#o#p&Q#p#q#P#q#r&V#r#y#P#y#z#k#z$f#P$f$g#k$g#BY#P#BY#BZ#k#BZ$IS#P$IS$I_#k$I_$I|#P$I|$JO#k$JO$JT#P$JT$JU#k$JU$KV#P$KV$KW#k$KW&FU#P&FU&FV#k&FV;'S#P;'S;=`#e<%lO#PP#UTUPO#o#P#p#q#P#r;'S#P;'S;=`#e<%lO#PP#hP;=`<%l#PR#riSQUPOX#PX^#k^p#Ppq#kq#o#P#p#q#P#r#y#P#y#z#k#z$f#P$f$g#k$g#BY#P#BY#BZ#k#BZ$IS#P$IS$I_#k$I_$I|#P$I|$JO#k$JO$JT#P$JT$JU#k$JU$KV#P$KV$KW#k$KW&FU#P&FU&FV#k&FV;'S#P;'S;=`#e<%lO#PR%hWUPTQO!c#P!c!}%a!}#T#P#T#o%a#p#q#P#r;'S#P;'S;=`#e<%lO#P~&VOY~~&[OZ~",
  tokenizers: [0, 1],
  topRules: {"TemplateString":[0,1]},
  tokenPrec: 0
})
